<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ngz.markov</groupId>
        <artifactId>markov-parent</artifactId>
        <version>2</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <groupId>ngz.extraction</groupId>
    <artifactId>filesink-awsbucket</artifactId>
    <version>0.1.0</version>

    <name>filesink-awsbucket</name>

    <properties>
        <aws.java.sdk.version>2.47.2</aws.java.sdk.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${aws.java.sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>ngz.extraction</groupId>
            <artifactId>extraction-core</artifactId>
            <version>0.1.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/software.amazon.awssdk/s3 -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-core</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>
        <pluginManagement>
        </pluginManagement>
    </build>
</project>
