export ETL_JOBID=EXTRACT-MFAROME
export ETL_SOURCE_PREVINUM=DPPaquetAROME-OM
export ETL_SOURCE_MODEL=AROME-OM-NCALED
export ETL_SOURCE_GRID=0.025
export ETL_SOURCE_PACKAGENAMES=SP1
export ETL_SOURCE_STARTTIME=2026-07-20T23:00:00Z
export ETL_SOURCE_ENDTIME=2026-07-21T05:00:00Z

export ETL_SOURCE_APPLICATIONID=

export ETL_SINK_BUCKET=cloudconfidence414-landing-zone
export ETL_SINK_BASEDIRECTORY=extraction/meteofrance-paquet

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_REGION=eu-north-1